import { ExportDownloadLink } from './download-link'

const thStyle: React.CSSProperties = {
  padding: '8px 12px',
  fontSize: 12,
  fontWeight: 600,
  borderBottom: '1px solid var(--border)',
  textAlign: 'left',
}

const tdStyle: React.CSSProperties = {
  padding: '8px 12px',
  fontSize: 14,
}

export interface ExportRow {
  id: string
  report_month: number
  report_year: number
  generated_at: string
  generated_by: string | null
  transaction_count: number
  product_count: number
  file_hash: string | null
}

function formatTime(value: string): string {
  const d = new Date(value)
  if (Number.isNaN(d.getTime())) return '-'
  return d.toLocaleString()
}

// History tab: newest-first list of stored export snapshots.
export function HistoryTab({ exports }: { exports: ExportRow[] }) {
  if (exports.length === 0) {
    return <p style={{ color: 'var(--text-secondary)', fontSize: 14 }}>No exports yet.</p>
  }

  return (
    <table style={{ width: '100%', borderCollapse: 'collapse', background: 'var(--card)' }}>
      <thead>
        <tr style={{ textAlign: 'left', color: 'var(--text-secondary)' }}>
          <th style={thStyle}>Month</th>
          <th style={thStyle}>Year</th>
          <th style={thStyle}>Generated At</th>
          <th style={thStyle}>Generated By</th>
          <th style={thStyle}>Rows</th>
          <th style={thStyle}>Hash</th>
          <th style={thStyle}></th>
        </tr>
      </thead>
      <tbody>
        {exports.map((e) => (
          <tr key={e.id} style={{ borderTop: '1px solid var(--border)' }}>
            <td style={tdStyle}>{e.report_month}</td>
            <td style={tdStyle}>{e.report_year}</td>
            <td style={tdStyle}>{formatTime(e.generated_at)}</td>
            <td style={tdStyle}>{e.generated_by || '-'}</td>
            <td style={tdStyle}>{e.product_count}</td>
            <td style={{ ...tdStyle, fontSize: 12, color: 'var(--text-secondary)' }}>
              {e.file_hash ? e.file_hash.slice(0, 8) : '-'}
            </td>
            <td style={tdStyle}>
              <ExportDownloadLink exportId={e.id} />
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}
