import { ExportDownloadLink } from './download-link'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'

export interface ExportRow {
  id: string
  report_month: number
  report_year: number
  generated_at: string
  generated_by: string | null
  transaction_count: number
  product_count: number
  file_hash: string | null
}

function formatTime(value: string): string {
  const d = new Date(value)
  if (Number.isNaN(d.getTime())) return '-'
  return d.toLocaleString()
}

// History tab: newest-first list of stored export snapshots.
export function HistoryTab({ exports }: { exports: ExportRow[] }) {
  if (exports.length === 0) {
    return <p className="text-sm text-slate-500">No exports yet.</p>
  }

  return (
    <div className="overflow-hidden rounded-xl bg-card ring-1 ring-foreground/10">
      <Table>
        <TableHeader className="bg-slate-50">
          <TableRow>
            <TableHead>Month</TableHead>
            <TableHead>Year</TableHead>
            <TableHead>Generated At</TableHead>
            <TableHead>Generated By</TableHead>
            <TableHead>Rows</TableHead>
            <TableHead>Hash</TableHead>
            <TableHead></TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {exports.map((e) => (
            <TableRow key={e.id} className="h-10">
              <TableCell>{e.report_month}</TableCell>
              <TableCell>{e.report_year}</TableCell>
              <TableCell>{formatTime(e.generated_at)}</TableCell>
              <TableCell>{e.generated_by || '-'}</TableCell>
              <TableCell>{e.product_count}</TableCell>
              <TableCell className="text-xs text-slate-500">
                {e.file_hash ? e.file_hash.slice(0, 8) : '-'}
              </TableCell>
              <TableCell>
                <ExportDownloadLink exportId={e.id} />
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  )
}
